### ISSUE TITLE
Update eslint so it runs/works?

### ISSUE THREAD

**Issue by bradtaniguchi** [JLuboff/connect-mssql-v2#22]
I know there is only 1 file to lint, but this project also includes **some** of what is needed to lint it (eslint+some plugins). We can setup linting to lint that single file (and potentially any other future files if need be)

As of right now the eslint configuration makes a command like `npx eslint src` not see any files due to the files being `.ts`. This can be fixed (along with any other lint errors) and will help us later if we ever add ci/cd support

**Comment by JLuboff** [comment]
Closing as this was fixed in the latest PR by adding --ext .ts
