### ISSUE TITLE
Add ts/es-lint, prettier on-commit hooks

### ISSUE THREAD

**Issue by bradtaniguchi** [JLuboff/connect-mssql-v2#3]
This will automatically enforce styling and linting guidelines on commit. See here for an example project: https://github.com/cmccormack/minesweeper

**Comment by JLuboff** [comment]
@bradtaniguchi This one is good to close with the latest PR, right?

**Comment by bradtaniguchi** [comment]
Ah yes, this has been closed with:
#25 #23
