### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by bradtaniguchi** [JLuboff/connect-mssql-v2#43]
We can add issue templates by following these docs:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

Having the following templates would be useful to cover the most common cases:
1. Report Bug
2. Request Enhancement/Feature

**Comment by JLuboff** [comment]
Added Bug and Feature Request templates: 2df7e5167e526b16eff748003ec3e5a1cc1fc595
